###########
#
# sqlmigrate設定ファイル
#
###########
aws:
    dialect: postgres
    dir: ./migrations
    table: migration
    datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PW}
development:
    dialect: postgres
    dir: ./migrations
    table: migration
    datasource: host=localhost port=35432 dbname=echo-household-budget user=postgres password=postgres sslmode=disable
test:
    dialect: postgres
    dir: ./migrations
    table: migration
    datasource: host=${TEST_DATABASE_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PW} sslmode=disable
