services:
  # docker exec -it echo-household-budget_db_1 /bin/sh
  # psql -U postgres -d echo-household-budget
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 35432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echo-household-budget
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # TODO : AWS Fargateを使用して、タスク定義作って、Fargateでmigrateする
  migrate:
    image: golang:1.20-alpine
    volumes:
      - ./migrations:/migrations
      - ./dbconfig.yml:/dbconfig.yml
    command: ["sql-migrate", "up", "-env=development"]
    depends_on:
      - db
