// Code generated by MockGen. DO NOT EDIT.
// Source: user_account_repository.go
//
// Generated by this command:
//
//	mockgen -source=user_account_repository.go -destination=../mock/repository/mock_user_account_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock
