@startuml

package ユーザー管理 {
  object ユーザーアカウント
  object ユーザーセッション
}

package 家計簿管理 {
  object 家計簿
  object カテゴリ設定 
  object 買い物メモ
  object 支出
}

package マスタ管理 {
  object カテゴリ
}


ユーザーセッション --* ユーザーアカウント
ユーザーアカウント --* 家計簿
カテゴリ --* 支出
カテゴリ --* 買い物メモ
カテゴリ設定 --* 家計簿
カテゴリ --* カテゴリ設定
@enduml
